version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: newzookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: newkafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  # kafka-manager:
  #   image: sheepkiller/kafka-manager
  #   container_name: kafka-manager
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     ZK_HOSTS: "zookeeper:2181"
  #   depends_on:
  #     - zookeeper
  #     - kafka

    #   KAFKA_CREATE_TOPICS: "test:1:1"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

    # Load the environment variables
    # docker-compose.yml up -d
    # docker ps

    # Unload the environment variables
    # docker-compose.yml down

    ##### docker exec -it kafka /bin/bash
    ##### start kafka
    # docker exec -it kafka /bin/sh

    # go to kafka directory
    # cd /opt/kafka/bin

    # Check the file list
    # ls

    # Create a topic
    # ./kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic test

    # list all topics
    # ./kafka-topics.sh --list --zookeeper zookeeper:2181

    # https://betterdatascience.com/how-to-install-apache-kafka-using-docker-the-easy-way/